audio:
  channels: 1
  chunk_size: 500
  format: paInt16
  sample_rate: 8000
current_server: 0
device:
  callsign: BH6XXX
  cpuid: '12345678'
  model: 1
  password: ''
  ssid: 1
network:
  buffer_size: 4096
  heartbeat_interval: 2
servers:
- host: 43.143.14.24
  name: 主服务器
  port: 60050
- host: 43.143.14.25
  name: 备用服务器
  port: 60050
