audio:
  channels: 1
  format: paInt16
  sample_rate: 8000
  tx_codec: "g711"
current_server: 0
device:
  callsign: BH6ERO
  dmr_id: '4613402'
  model: 1
  password: ''
  ssid: 1
network:
  buffer_size: 4096
  heartbeat_interval: 2
server:
  host: 43.143.14.24
  port: 60050
servers:
- host: 43.143.14.24
  name: NRL-安徽服务器
  password: ''
  port: 60050
- host: example2.com
  name: 示例服务器2
  password: ''
  port: 60050
- host: 127.0.0.1
  name: 本地测试服务器
  password: ''
  port: 60050
